= How to abort a run early

The most common way to end a run early is with the `abort` command.
```yaml
- sh: doSomething.sh
  watch:
  - regex: FATAL
    then:
    - abort: fatal error in doSomething.sh
```
By default, `abort` stops the `setup-scripts` and `run-scripts` but
qDup will still download anything that was queued with `queue-download` and by default it will still run the `cleanup-scripts`.
We can prevent the `cleanup-scripts` with the `skip-cleanup` option in the full command syntax.
```yaml
- sh: doSomething.sh
  watch:
  - regex: FATAL
    then:
    - abort:
        message: fatal error in doSomething.sh
        skip-cleanup: true
```

== exit codes
The other way to abort a run early is to check exit codes for `sh` commands.
qDup checks the exit code after every `sh` that uses the default prompt (not commands that end with prompts from `add-prompt`).
qDup will abort the run if the exit code is not 0. This can be disabled on an individual `sh` command with `ignore-exit-code: false`
```yaml
- sh:
    command: doSomething.sh
    ignore-exit-code: false
```
We can also tell qDup to ignore all exit codes with `-ix` or `--ignore-exit-code=true` command line arguments. There is also a global setting `check-exit-code: false` that can be included in the yaml.
```yaml
global:
  settings:
    check-exit-code: false
```