= How to pass secrets into qDup

qDup can treat state entries as secrets. This is most commonly used for usernames or passwords that are passed into qDup for authentication.

qDup recognizes a secret state entry by prefixing the name with an underscore (e.g. `_my-secret : passw0rd`). In this case, qDup will remove the underscore and store the entry as `my-secret` but it will filter out the value form any logs (or json).
The underscore prefix can be used any place where we set a sate value:

The command line:
```
-S _my-secret="passw0rd"
```
In yaml:
```
states:
  _my-secret: passw0rd
```
In a `regex` command:
```yaml:
- regex: "(?<_my-secret).*"
```
Or directly with a `set-state` command:

```yaml
- set-state: _my-secret
```

Storing the secret value (`passw0rd`) directly in the yaml does not help protect the secret.
A better option is to store a placeholder in yaml:
```yaml
states:
  my-password: "12345" #wrong password in yaml
```
Then pass in the correct value through the command line (note how the command line can also use environment variables).
```
-S _my-secret=${PASSWORD}
```

== Jenkins
Jenkins secrets use the same command line style but have the added benefit of storing the value as jenkins credentials.
The credentials can be accessed with either an `environment` section or in a `withCredentials` section:
```
environment {
  SECRET = credentials('my_secret_credentials')
}
...

```
```
withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId:'my_secret_credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
  ...
}
```
Credentials loaded using `environment` will automatically create different variables for the username and password. The username has a `_USR` suffix and the password has a `_PSW` suffix.
```
-S _my-secret=${SECRET_PSW}
```
Credentials loaded using `withCredentials` use the variable names you provide for username and password
```
-S _my-secret=${PASSWORD}
```
