= qDup hosts

The `hosts` section in qDup is a yaml mapping that assigns an alias for a username + host combination.

[source,yaml]
----
hosts:
  alias: me@myserver.com #logs in with ssh key using default port
----
The link:./roles.adoc[roles] then refer to host connections by the alias.
[source,yaml]
----
roles:
  example:
    hosts: [alias]
  ...
----

Hosts can be a string or mapping but in either case it must contain the information
necessary to connect to the remote host. The previous `alias` used ssh keys with the default
ssh port but a password and port number can be added to the configuration.
[source,yaml]
----
hosts:
  alias: me:12345@myserver.com:22
----
There is also a move verbose mapping format for those who like to write more yaml.
[source,yaml]
----
hosts:
  alias:
   username: me
   hostname: myserver.com
   port: 22
   password: 12345
----

qDup supports passwords in the hosts definition because it can make testing easier but ssh keys are the recommended login method.
If you cannot use ssh keys and must include the password you should use a state variable and pass the value as a secret through the command line

.qdup.yaml
[source,yaml]
----
hosts:
  alias: me:${{password}}@myserver.com:2222
----
Then run the script reading the password from a tmp file so it is not in the bash history
....
java -jar qdup-uber.jar -b /tmp/ -S _password="$(cat /tmp/secret.txt)" qdup.yaml
....
`-S _password` sets the state variable password and the `__` prefix tells qDup to treat the
value as a secret and replace it with `\****` in the logs.
