= qDup jar

the main way to run qDup is with the `qDup-uber.jar`. A slim jar without dependencies
is available when using the qDup java api.
....
java -jar qDup-uber.jar -b /tmp/ qdup.yaml util.yaml
....
qDup requires a working directory. The `-b /tmp/` tells qDup to create a working folder in the
`/tmp/` directory. Alternatively, we can use `-B /tmp/` to use `/tmp/` as the working directory.

The next required options are the YAML scripts themselves. qDup will load the files in their listed
order and will not overwrite scripts or hosts if they appear in more than one file.

qDup will merge role definitions one file can declare a role without hosts and then rely on
another file to add hosts to the role. A role will not run if it does not have hosts.

.qdup.yaml
[source,yaml]
----
hosts:
  server: me@myserver.com
roles:
  doit: #adds hosts to the role from util.yaml
    hosts: [server]
----

.util.yaml
[source,yaml]
----
scripts:
  setup:
  - sh: echo "just an example"
roles:
  doit: #will not run without adding hosts
    setup-scripts:
    - setup
----
....
java -jar qDup-uber.jar -B /tmp/ qdup.yaml util.yaml
....

== monitoring

qDup starts a JSON server for run monitoring and debug. The default port is `31337` but can be changed with `--jsonport`.
The endpoints are the following:

GET /state :: current qDup state
GET /stage :: the current run stage
GET /active :: list of active commands and context
GET /session :: list of active ssh terminal sessions
POST /session/:sessionId :: send text to the ssh terminal session. ^C sends ctrl+C
GET /signal :: get the signal and their remaining signal counts
POST /signal/:name :: set the remaining signal count for the target signal
GET /timer :: get the current command times
GET /waiter :: get the current waiters
GET /counter :: get the current counter counts
GET /pendingDownloads :: get the list of pending downloads

== logging configuration

Occasionally you will need to enable different logging levels than the default, for example for debugging the ssh handshake with a remote machine.  qDup uses log4j as its logging framework.

Create a new logging configuration (e.g. log4j.properties);

[source,text]
----
# Set to debug or trace if log4j initialization is failing
status = warn

# Name of the configuration
name = QdupConsoleLogConfigDebug

# Console appender configuration
appender.console.type = Console
appender.console.name = consoleDebugLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Root logger level
rootLogger.level = trace

# Root logger referring to console appender
rootLogger.appenderRef.stdout.ref = consoleDebugLogger
----

and start qDup with the new logging configuration

....
java -Dlog4j.configurationFile=log4j.properties  -jar qDup-uber.jar -B /tmp/ qdup.yaml util.yaml
....

