= qDup Hello World

== Prerequisites
qDup connects to computers through ssh. You need to have a computer that will accept ssh connections. You can setup ssh on your own computer by following the steps in the link:./prerequisites.adoc[prerequisites]

== qDup jar
qDup is distributed as an executable jar (Java's version of a zip). Download the latest `uber` jar from link:https://github.com/Hyperfoil/qDup/releases/latest[github]

== YAML script
qDup scripts use are saved as yaml. We can explore the yaml structure in later tutorials.
Use the following bash command to create a test yaml file.

The `$USER` variable will be replaced by the output of `echo $USER`. You can check by inspecting the yaml file content.
```
#> cat <<EOF > helloworld.yaml
scripts:
    tryme:
    - sh: whoami
    - sh: date
    - sh: echo ${{message}}
hosts:
    server: $USER@localhost
roles:
    test:
        hosts:
        - server
        run-scripts:
        - tryme
states:
    message: Hello, qDup!
EOF
```

== Run qDup

If you followed the previous link:./prerequisites.adoc[prerequisites] tutorial and create a new identify file name `qdup` then we need to tell qDup to use that instead of the default identify file.
```
#> java -jar qDup-0.8.5-uber.jar -i ~/.ssh/qdup helloworld.yaml

13:45:49.696 Running qDup version 0.8.5 @ d66bc67
13:45:49.697 output path = /tmp/20250107_134548
13:45:49.697 shell exit code checks enabled
13:45:49.822 json server listening at user-host:31337
13:45:51.474 starting 1 scripts
13:45:51.477 tryme:20@localhost: script-cmd: tryme
13:45:51.478 tryme:20@localhost: tryme
13:45:51.891 tryme:20@localhost: whoami
testuser
13:45:52.304 tryme:20@localhost: date
Tue Jan  7 01:45:51 PM -03 2025
13:45:52.717 tryme:20@localhost: echo Hello, qDup!
Hello, qDup!
Finished in 02.885 at /tmp/20250107_134548

```

== Changing the greeting

The `- sh: echo ${{message}}` command uses pattern substitution. qDup uses the `states` value for `message` but we can change that when running qDup by passing in a different value for `message` through the command line.
```
#> java -jar qDup-0.8.5-uber.jar -i ~/.ssh/qdup -S message="howdy, qDup" helloworld.yaml

13:48:21.077 Running qDup version 0.8.5 @ d66bc67
13:48:21.078 output path = /tmp/20250107_134819
13:48:21.078 shell exit code checks enabled
13:48:21.198 json server listening at user-host:31337
13:48:22.308 starting 1 scripts
13:48:22.311 tryme:20@localhost: script-cmd: tryme
13:48:22.312 tryme:20@localhost: tryme
13:48:22.726 tryme:20@localhost: whoami
testuser
13:48:23.139 tryme:20@localhost: date
Tue Jan  7 01:48:22 PM -03 2025
13:48:23.554 tryme:20@localhost: echo howdy, qDup
howdy, qDup
Finished in 02.344 at /tmp/20250107_134819

```
The `-S` argument overrides the value in yaml. We can store a default in yaml then use the command line to customize the script execution.

NOTE: We use the `-S` command line argument to pass jenkins parameters into qDup executions.

Each run ended with a message about `Finished in 02.0xx at /tmp/...` where the `...` is the output folder.  Let's explore the content.

```
#> tree /tmp/20221005_220316
/tmp/20221005_220316
├── run.json
└── run.log

0 directories, 2 files
```
The output folder will eventually contain any files we download as part of our scripts. Right now it has 2 files:

* *run.log* contains everything that was logged by qDup during the run. This is a copy of what qDup logs to the terminal and servers as review of all the command qDup ran.
* *run.json* contains a structured summary of the run. It includes timestamps for when qDup started and when each command in the script executed as well as internal qDup state.

== Next
At this point you can run a qDup script but our script is very simple. Try the link:./quarkusgetstarted.adoc[next tutorial] to see how we can script deploying and test a Quarkus application.
